config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :products do
      resources :videos do
        collection do
          post :update_positions
        end
      end
    end
  end
end

app/models/product_decorator.rb
Product.class_eval do
  has_many :videos, :as => :viewable, :order => :position, :dependent => :destroy
end

app/models/variant_decorator.rb
Variant.class_eval do
  has_many :videos, :as => :viewable, :order => :position, :dependent => :destroy
end

app/models/video.rb
require 'ostruct'

class Video < ActiveRecord::Base
  belongs_to :viewable, :polymorphic => true

  before_save :update_metadata

  validates :url, :presence => true
  validates_each :url do |model, attr, value|
    if value.present?
      begin
        oembed_response = model.oembed_cached()
        unless oembed_response.type == 'video'
          model.errors.add(attr, I18n.t("video_invalid_url"))
        end
      rescue OEmbed::UnknownResponse
        model.errors.add(attr, I18n.t("video_unknown_response"))
      rescue OEmbed::NotFound
        model.errors.add(attr, I18n.t("video_invalid_url"))
      end
    end
  end

  def embed_html(maxwidth = nil)
    oembed_cached(maxwidth).html
  end

  def oembed_cached(maxwidth = nil)
    Rails.cache.fetch(oembed_cache_key(maxwidth), :expires_in => 1.hour) do
      options = {}
      options["maxwidth"] = maxwidth if maxwidth

      provider = OEmbed::Providers.find(url)

      # If embedly is the chosen provider and is configured, set an api key in the options
      if provider && provider.endpoint.include?("embed.ly") && SpreeEmbeddedVideos::Config.embedly_api_key
        options["key"] = SpreeEmbeddedVideos::Config.embedly_api_key
      end

      response = nil
      if provider
        response = provider.get(url, options)
      end
      response.nil? ? nil : OpenStruct.new(response.fields).freeze
    end
  end

  private
  def update_metadata
    if url.present?
      oembed_response = oembed_cached

      Rails.logger.info(oembed_response.inspect)

      if oembed_response.type == 'video'
        self.title = oembed_response.title
        self.thumbnail_url = oembed_response.thumbnail_url
        self.thumbnail_width = oembed_response.thumbnail_width
        self.thumbnail_height = oembed_response.thumbnail_height
      else
        raise "Error updating metadata - URL is not a video URL."
      end
    end
  end

  def oembed_cache_key(maxwidth = nil)
    if maxwidth
      "video:oembed:#{url}:#{maxwidth}"
    else
      "video:oembed:#{url}"
    end
  end

end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::ResourceController
  before_filter :load_data

  create.before :set_viewable
  update.before :set_viewable
  destroy.before :destroy_before

  def update_positions
    params[:positions].each do |id, index|
      Video.update_all(['position=?', index], ['id=?', id])
    end

    respond_to do |format|
      format.js  { render :text => 'Ok' }
    end
  end

  private
  
  def location_after_save
    admin_product_videos_url(@product)
  end

  def load_data
    @product = Product.find_by_permalink(params[:product_id])
    @variants = @product.variants.collect do |variant|
      [variant.options_text, variant.id ]
    end
    @variants.insert(0, [I18n.t("all"), "All"])
  end

  def set_viewable
    if params[:video].has_key? :viewable_id
      if params[:video][:viewable_id] == "All"
        @video.viewable = @product
      else
        @video.viewable_type = 'Variant'
        @video.viewable_id = params[:video][:viewable_id]
      end
    else
      @video.viewable = @product
    end
  end

  def destroy_before
    @viewable = @video.viewable
  end

end

app/views/admin/videos/_form.html.erb
<% if @product.has_variants? %>
  <tr>
    <td><%= Variant.model_name.human %>:</td>
    <td><%= f.select :viewable_id, @variants %></td>
  </tr>
<% else %>
  <%= hidden_field_tag :product_id, @product.id %>
<% end %>
<tr>
  <td><%= t("url") %>:</td>
  <td><%= f.text_field :url %></td>
</tr>

app/views/admin/videos/_menu_item.html.erb
<li<%== ' class="active"' if current == "Videos" %>>
  <%= link_to t("videos"), admin_product_videos_url(@product) %>
</li>

app/views/admin/videos/edit.html.erb
<%= render :partial => 'admin/shared/product_sub_menu' %>

<%= render :partial => 'admin/shared/product_tabs', :locals => {:current => "Videos"} %>

<p><%=t("video_description")%></p>

<%= render "shared/error_messages", :target => @video %>

<%= form_for(:video, :url => admin_product_video_url(@product), :html => { :method => :put, :multipart => true }) do |f| %>
  <table class="basic-table">
    <% if @video.thumbnail_url and @video.errors.empty? %>
      <tr>
        <td><%= t("video") %>:</td>
        <td>
            <%= @video.embed_html(240).html_safe %>
        </td>
      </tr>
    <% end %>
    <%= render :partial => "form", :locals => { :f => f } %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    <%= t('or') %> <%= link_to t("cancel"), admin_product_videos_url(@product), :id => "cancel_link" %>
  </p>
<% end %>

app/views/admin/videos/index.html.erb
<%= render :partial => 'admin/shared/product_sub_menu' %>

<%= render :partial => 'admin/shared/product_tabs', :locals => {:current => "Videos"} %>

<table class="index sortable">
  <thead>
    <tr>
      <th><%= t("video") %></th>
      <% if @product.has_variants? %>
        <th><%= Variant.model_name.human %></th>
      <% end %>
      <th><%= t("title") %></th>
      <th><%= t("action") %></th>
    </tr>
  </thead>
  <tbody>
    <% @product.videos.each do |video| %>
      <tr id="<%= dom_id(video) %>">
        <td>
          <span class="handle"></span>
          <%= image_tag(video.thumbnail_url, :width => 100) %>
        </td>
        <% if @product.has_variants? %>
          <td><%= t('all') %></td>
        <% end %>
        <td><%= video.title %></td>

        <td class="actions">
          <%= link_to_with_icon('edit', t("edit"), edit_admin_product_video_url(@product, video), :class => 'edit') %>
          &nbsp;
          <%= link_to_delete video, {:url => admin_product_video_url(@product, video) }%>
        </td>
      </tr>
    <% end %>

    <% @product.variants.each do |variant| %>
      <% variant.videos.each do |video| %>
        <tr id="<%= dom_id(video) %>">
          <td>
            <span class="handle"></span>
            <%= image_tag(video.thumbnail_url, :width => 100) %>
          </td>
          <% if @product.has_variants? %>
            <td><%= variant.options_text %></td>
          <% end %>
          <td><%= video.title %></td>
          <td class="actions">
            <%= link_to_with_icon('edit', t("edit"), edit_admin_product_video_url(@product, video)) %>
            &nbsp;
            <%= link_to_delete video, {:url => admin_product_video_url(@product, video) }%>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<div id="videos"></div>
<br/>
<p>
    <%= link_to icon('add') + ' ' + t("new_video"), new_admin_product_video_url(@product), :id => "new_video_link" %>
</p>

<% content_for :head do %>
  <script type="text/javascript">
    jQuery(document).ready(function(){

      jQuery('#new_video_link').click(function (event) {
        event.preventDefault();
        jQuery(this).hide();
        jQuery.ajax({type: 'GET', url: this.href, data: ({authenticity_token: AUTH_TOKEN}), success: function(r){ jQuery('#videos').html(r);} });
      });

    });
  </script>
<% end %>

app/views/admin/videos/new.html.erb
<h4><%= t("new_video") %></h4>
<p><%=t("video_description")%></p>

<%= render "shared/error_messages", :target => @video %>

<%= form_for(:video, :url => { :controller => 'videos', :action => 'create' }, :html => { :multipart => true }) do |form| %>
  <table class="basic-table">
    <%= render :partial => "form", :locals => { :f => form } %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    <%= t('or') %> <%= link_to t("cancel"), "#", :id => "cancel_link" %>
  </p>
<% end %>


<script type="text/javascript">    
  jQuery('#cancel_link').click(function (event) { 
    jQuery('#new_video_link').show();
    jQuery('#videos').html('');
  });
</script>

 
 

app/views/products/_thumbnail_items.html.erb
<% hidden ||= false %>

<ul id="<%= list_id %>" class="thumbnails" style="<%= hidden ? 'display: none' : '' %>">
  <% images.each do |i| %>
    <li id="image_<%=i.id%>" class="image"><%= link_to(image_tag(i.attachment.url(:mini)), i.attachment.url(:product)) %></li>
    <script type="text/javascript">
      $('#image_<%=i.id%>').data('content', <%==image_tag(i.attachment.url(:product)).to_json %>);
    </script>
  <% end %>

  <% videos.each do |v| %>
    <li id="video_<%=v.id%>" class="video">
      <%= link_to(image_tag(v.thumbnail_url), v.thumbnail_url) %>
      <span>Video</span>
    </li>
    <script type="text/javascript">
      $('#video_<%=v.id%>').data('content', <%== v.embed_html(240).to_json %>);
    </script>
  <% end %>
</ul>

app/views/products/_thumbnails.html.erb
<%= render :partial => 'thumbnail_items', :locals => {:list_id => 'product-thumbnails', :images => @product.images, :videos => @product.videos } %>

<% if @product.has_variants? %>
  <% @variants.each do |v| %>
    <% if v.available? %>
      <%= render :partial => 'thumbnail_items', :locals => {:list_id => "variant-thumbnails-#{v.id}", :hidden => true, :images => v.images, :videos => v.videos } %>
    <% end %>
  <% end %>
<% end %>

<% content_for :head do %>
  <%= stylesheet_link_tag 'videos' %>
<% end %>